<?php
/**
 * @file
 * islandora_preservation_documentation.features.content_menu_links.inc
 */

/**
 * Implements hook_content_menu_links_defaults().
 */
function islandora_preservation_documentation_content_menu_links_defaults() {
  $menu_links = array();

  // Exported menu link: menu-preservation-documentation:node/7
  $menu_links['menu-preservation-documentation:node/7'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-definition-of-aip',
    'router_path' => 'node/%',
    'link_title' => 'Definition of AIP',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_definition-of-aip:node/7',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/8
  $menu_links['menu-preservation-documentation:node/8'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-definition-of-dip',
    'router_path' => 'node/%',
    'link_title' => 'Definition of DIP',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_definition-of-dip:node/8',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/9
  $menu_links['menu-preservation-documentation:node/9'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-definition-of-sip',
    'router_path' => 'node/%',
    'link_title' => 'Definition of SIP',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_definition-of-sip:node/9',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/11
  $menu_links['menu-preservation-documentation:node/11'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-digital-preservation-designated-community-definition',
    'router_path' => 'node/%',
    'link_title' => 'Digital Preservation Designated Community Definition',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_digital-preservation-designated-community-definition:node/11',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/12
  $menu_links['menu-preservation-documentation:node/12'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-digital-preservation-implementation-plan',
    'router_path' => 'node/%',
    'link_title' => 'Digital Preservation Implementation Plan',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_digital-preservation-implementation-plan:node/12',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/13
  $menu_links['menu-preservation-documentation:node/13'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-digital-preservation-rights-policy',
    'router_path' => 'node/%',
    'link_title' => 'Digital Preservation Rights Policy',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_digital-preservation-rights-policy:node/13',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/14
  $menu_links['menu-preservation-documentation:node/14'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-digital-preservation-strategic-plan',
    'router_path' => 'node/%',
    'link_title' => 'Digital Preservation Strategic Plan',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_digital-preservation-strategic-plan:node/14',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/15
  $menu_links['menu-preservation-documentation:node/15'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-environmental-monitoring-of-preservation-formats',
    'router_path' => 'node/%',
    'link_title' => 'Environmental Monitoring of Preservation Formats',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_environmental-monitoring-of-preservation-formats:node/15',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/16
  $menu_links['menu-preservation-documentation:node/16'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-fixity-procedures',
    'router_path' => 'node/%',
    'link_title' => 'Fixity procedures',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_fixity-procedures:node/16',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/10
  $menu_links['menu-preservation-documentation:node/10'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-registry-of-file-formats',
    'router_path' => 'node/%',
    'link_title' => 'Registry of file formats',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_registry-of-file-formats:node/10',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/17
  $menu_links['menu-preservation-documentation:node/17'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/policy-url-and-file-naming-policy',
    'router_path' => 'node/%',
    'link_title' => 'URL and File Naming Policy',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_url-and-file-naming-policy:node/17',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/18
  $menu_links['menu-preservation-documentation:node/18'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/preservation-action-plans-audio',
    'router_path' => 'node/%',
    'link_title' => 'Audio - Preservation Action Plan',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_audio---preservation-action-plan:node/18',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/19
  $menu_links['menu-preservation-documentation:node/19'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/preservation-action-plans-image',
    'router_path' => 'node/%',
    'link_title' => 'Image - Preservation Action Plan',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_image---preservation-action-plan:node/19',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/20
  $menu_links['menu-preservation-documentation:node/20'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/preservation-action-plans-theses',
    'router_path' => 'node/%',
    'link_title' => 'Theses - Preservation Action Plan',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_theses---preservation-action-plan:node/20',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/21
  $menu_links['menu-preservation-documentation:node/21'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/preservation-action-plans-video',
    'router_path' => 'node/%',
    'link_title' => 'Video - Preservation Action Plan',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_video---preservation-action-plan:node/21',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation:node/22
  $menu_links['menu-preservation-documentation:node/22'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => 'node-name/preservation-action-plans-warc',
    'router_path' => 'node/%',
    'link_title' => 'Web Archives - Preservation Action Plan',
    'options' => array(
      'identifier' => 'menu-preservation-documentation_web-archives---preservation-action-plan:node/22',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_path' => '<front>',
  );
  // Exported menu link: menu-preservation-documentation_policies:<front>
  $menu_links['menu-preservation-documentation_policies:<front>'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Policies',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-preservation-documentation_policies:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-preservation-documentation_preservation-action-plans:<front>
  $menu_links['menu-preservation-documentation_preservation-action-plans:<front>'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Preservation Action Plans',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-preservation-documentation_preservation-action-plans:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-preservation-documentation_preservation-documentation:<front>
  $menu_links['menu-preservation-documentation_preservation-documentation:<front>'] = array(
    'menu_name' => 'menu-preservation-documentation',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Preservation Documentation',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-preservation-documentation_preservation-documentation:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Audio - Preservation Action Plan');
  t('Definition of AIP');
  t('Definition of DIP');
  t('Definition of SIP');
  t('Digital Preservation Designated Community Definition');
  t('Digital Preservation Implementation Plan');
  t('Digital Preservation Rights Policy');
  t('Digital Preservation Strategic Plan');
  t('Environmental Monitoring of Preservation Formats');
  t('Fixity procedures');
  t('Image - Preservation Action Plan');
  t('Policies');
  t('Preservation Action Plans');
  t('Preservation Documentation');
  t('Registry of file formats');
  t('Theses - Preservation Action Plan');
  t('URL and File Naming Policy');
  t('Video - Preservation Action Plan');
  t('Web Archives - Preservation Action Plan');


  return $menu_links;
}
